### ISSUE TITLE
Error if path has spaces

### ISSUE THREAD

**Issue by dgsmith2** [ReactiveX/rxjs-tslint#25]
If your project has a space in its path the call to `execSync` will fail because the unescaped space(s) causes the remainder of the command to be interpreted as command-line argument(s).

**Comment by mgechev** [comment]
@dgsmith2 this doesn't seem to solve:

```bash
rxjs-5-to-6-migrate -p path\ to\ your/tsconfig.json
```

**Comment by JamesJansson** [comment]
This issue needs to be reopened, because it really is a bug that needs to be resolved for Windows users. The file path is not just unescaped for tsconfig, but also the tslint and the rxjs-5-to-6migrate.json, and uses absolute paths.

If, for example, your user name in Winddows is "First Last", your path will look like "C:\User\First Last\..." for all of the above files, breaking the install.

**Comment by JamesJansson** [comment]
I've made a pull request that should fix this issue.

**Comment by JamesJansson** [comment]
I just looked, there's a week old PR from dgsmith2 with almost exactly the same issue. The failure to accept this PR will be stopping a lot of people from upgrading to Angular 6. It's a hot topic off the back off IO18, so this should be seen to sooner rather than later.

**Comment by somnathswami** [comment]
yes this issue is big barrier to migrate angular 5 to angular 6 :(

**Comment by mgechev** [comment]
Fixed and published as part of 0.1.4.
